# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: factory-pattern
description: Example indexer for indexing factory-deployed contracts
contracts:
    - name: UniswapV3Factory
      handler: src/EventHandlers.ts
      events:
          - event: PoolCreated(address indexed token0, address indexed token1, uint24 indexed fee, int24 tickSpacing, address pool)
    - name: UniswapV3Pool
      handler: src/EventHandlers.ts
      events:
          - event: Swap(address indexed sender, address indexed recipient, int256 amount0, int256 amount1, uint160 sqrtPriceX96, uint128 liquidity, int24 tick)

networks:
    - id: 1
      start_block: 0
      contracts:
          - name: UniswapV3Factory
            address:
                - 0x1F98431c8aD98523631AE4a59f267346ea31F984
          - name: UniswapV3Pool
unordered_multichain_mode: true
preload_handlers: true
