# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: Wildcard Indexing
description: Index all events matching a specified event signature without requiring the contract address
networks:
    - id: 1 # Ethereum Mainnet
      start_block: 23480542
      contracts:
          - name: ERC20
            handler: src/EventHandlers.ts
            events:
                - event: "Transfer(address indexed from, address indexed to, uint256 value)"

# https://docs.envio.dev/docs/HyperIndex/multichain-indexing#unordered-multichain-mode
unordered_multichain_mode: true
preload_handlers: true